### ISSUE TITLE
Not compatible with the current version of Julia

### ISSUE THREAD

**Issue by rohitpatra** [wenyuC94/ConvexRegression#1]
Hey Wenyu, 

We were trying use this code and the codes are not compatible with the current version of Julia (1.5). Is there anyway you could fix that? We are not very familiar with Julia and were trying to use it via JuliaCall package in R. Thanks for all the great work. 
Best,
Rohit

**Comment by wenyuC94** [comment]
> Hey Wenyu,
> 
> We were trying use this code and the codes are not compatible with the current version of Julia (1.5). Is there anyway you could fix that? We are not very familiar with Julia and were trying to use it via JuliaCall package in R. Thanks for all the great work.
> Best,
> Rohit

Hi Rohit, 

Thanks for raising this issue to us. We will try to look into this as soon as we get time. 

Best,
Wenyu
